version: '3.7'

services:
  web-loteria:
    image: nginx:stable-alpine3.19-slim
    container_name: web_loteria_v1.0
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_loteria
    ports:
      - "8500:80"
    networks:
      - red-gane-int

  api_loteria:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: loteria-server_v1.0
    image: loteria-server:v1
    networks:
      red-gane-int:
        aliases:
          - loteriaserver_v1.0
    environment:
      - TZ=America/Bogota

networks:
  red-gane-int:
    external: true
